name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - conda=4.10.1
  - conda-build=3.20.5
  - conda-verify=3.4.2
  - jupyter=1.0.0
  - jupyterlab=2.2.6
  - hvplot=0.7.1
  - json5=0.9.5
  - xarray
  - numpy
  - metpy
  - cartopy
  - seawater=3.3.4
  - gsw
  - warnings
